cc_library(
        name = "singlenightstarobservationscheduling",
        hdrs = ["singlenightstarobservationscheduling.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:info",
        ],
        visibility = ["//visibility:public"],
)
