name: Build

on: [push]

jobs:

  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download data
      run: |
        python3 -m pip install gdown
        python3 -u scripts/download_data.py
    - name: Build Linux
      run: bazel build -- //...
      if: matrix.os != 'windows-latest'
    - name: Build Windows
      run: bazel build  --cxxopt=/MT -- //...
      if: matrix.os == 'windows-latest'
    - name: Run tests
      run: python3 -u scripts/run_tests.py test_results
      env:
        DYLD_LIBRARY_PATH: ./bazel-columngenerationsolver/external/clp_darwin/lib/
    - name: Checkout main branch
      run: |
        git remote set-branches origin '*'
        git fetch --depth 1
        git checkout main
    - name: Build Linux
      run: bazel build -- //...
      if: matrix.os != 'windows-latest'
    - name: Build Windows
      run: bazel build  --cxxopt=/MT -- //...
      if: matrix.os == 'windows-latest'
    - name: Run tests
      run: python3 -u scripts/run_tests.py test_results_ref
      env:
        DYLD_LIBRARY_PATH: ./bazel-columngenerationsolver/external/clp_darwin/lib/
    - name: Process tests
      run: python3 -u ./bazel-columngenerationsolver/external/optimizationtools/scripts/process_tests.py --ref test_results_ref --new test_results
