name: Build

on: [push]

jobs:

  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8"]

    env:
      CUTTING_STOCK_DATA: ${{ github.workspace }}/data/cutting_stock
      MULTIPLE_KNAPSACK_DATA: ${{ github.workspace }}/data/multiple_knapsack
      BIN_PACKING_WITH_CONFLICTS_DATA: ${{ github.workspace }}/data/bin_packing_with_conflicts
      CAPACITATED_VEHICLE_ROUTING_DATA: ${{ github.workspace }}/data/capacitated_vehicle_routing
      VEHICLE_ROUTING_WITH_TIME_WINDOWS_DATA: ${{ github.workspace }}/data/vehicle_routing_with_time_windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download data
      run: |
        python3 -m pip install gdown
        python3 -u scripts/download_data.py
    - name: Build
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release --parallel
        cmake --install build --config Release --prefix install
    - name: Copy CLP libraries (Darwin)
      run: |
        mkdir -p "/Users/runner/work/Osi/Osi/dist/lib"
        cp -rf "${GITHUB_WORKSPACE}/build/_deps/mathoptsolverscmake-build/extern/Osi-prefix/src/Osi/lib/" "/Users/runner/work/Osi/Osi/dist/lib"
        mkdir -p "/Users/runner/work/CoinUtils/CoinUtils/dist/lib"
        cp -rf "${GITHUB_WORKSPACE}/build/_deps/mathoptsolverscmake-build/extern/CoinUtils-prefix/src/CoinUtils/lib/" "/Users/runner/work/CoinUtils/CoinUtils/dist/lib"
        mkdir -p "/Users/runner/work/Clp/Clp/dist/lib"
        cp -rf "${GITHUB_WORKSPACE}/build/_deps/mathoptsolverscmake-build/extern/Clp-prefix/src/Clp/lib/" "/Users/runner/work/Clp/Clp/dist/lib"
      if: matrix.os == 'macos-latest'
    - name: Run tests
      run: python3 -u scripts/run_tests.py test_results
    - name: Checkout main branch
      run: |
        git remote set-branches origin '*'
        git fetch --depth 1
        git checkout main
    - name: Build Linux
      run: bazel build -- //examples/...
      if: matrix.os != 'windows-latest'
    - name: Build Windows
      run: bazel build  --cxxopt=/MT -- //examples/...
      if: matrix.os == 'windows-latest'
    - name: Copy CLP libraries (Darwin)
      run: |
        mkdir -p "/Users/runner/work/Osi/Osi/dist/lib"
        cp -rf "${GITHUB_WORKSPACE}/bazel-columngenerationsolver/external/osi_darwin/lib/" "/Users/runner/work/Osi/Osi/dist/lib"
        mkdir -p "/Users/runner/work/CoinUtils/CoinUtils/dist/lib"
        cp -rf "${GITHUB_WORKSPACE}/bazel-columngenerationsolver/external/coinutils_darwin/lib/" "/Users/runner/work/CoinUtils/CoinUtils/dist/lib"
        mkdir -p "/Users/runner/work/Clp/Clp/dist/lib"
        cp -rf "${GITHUB_WORKSPACE}/bazel-columngenerationsolver/external/clp_darwin/lib/" "/Users/runner/work/Clp/Clp/dist/lib"
      if: matrix.os == 'macos-latest'
    - name: Run tests
      run: python3 -u scripts/run_tests.py test_results_ref
    - name: Process tests
      run: python3 -u ./build/_deps/optimizationtools-src/scripts/process_tests.py --ref test_results_ref --new test_results
